### ISSUE TITLE
Protocol selection failed testing new protocol (Chat)

### ISSUE THREAD

**Issue by brokenprogrammer** [feldmanchain/feldmanchain-on-prem#8]
Tried to run the application and got the following error message:

```cmd
> feldmanchain-on-prem@1.0.0 start
> node ./src/peer.js

Listener ready, listening on:
/ip4/192.168.81.24/tcp/61111/p2p/QmeVH7fbKuiLyz3agCELWQb1fHy7tSoY4PSCwnbpyTHPVZ
/ip4/192.168.56.1/tcp/61111/p2p/QmeVH7fbKuiLyz3agCELWQb1fHy7tSoY4PSCwnbpyTHPVZ
/ip4/127.0.0.1/tcp/61111/p2p/QmeVH7fbKuiLyz3agCELWQb1fHy7tSoY4PSCwnbpyTHPVZ


Discovered: 12D3KooWQu3wjQYbi23VVZCvxV9Ta3Tu4Z4fwuat69Zydn4apEWR


C:\Users\oskar.mendel\Documents\Github\feldmanchain-on-prem\node_modules\multistream-select\src\select.js:50
  throw errCode(new Error('protocol selection failed'), 'ERR_UNSUPPORTED_PROTOCOL')
                ^

Error: protocol selection failed
    at module.exports (C:\Users\oskar.mendel\Documents\Github\feldmanchain-on-prem\node_modules\multistream-select\src\select.js:50:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.newStream [as _newStream] (C:\Users\oskar.mendel\Documents\Github\feldmanchain-on-prem\node_modules\libp2p\src\upgrader.js:251:40)
    at async Connection.newStream (C:\Users\oskar.mendel\Documents\Github\feldmanchain-on-prem\node_modules\libp2p-interfaces\src\connection\connection.js:173:34)
    at async Libp2p.<anonymous> (file:///C:/Users/oskar.mendel/Documents/Github/feldmanchain-on-prem/src/peer.js:48:22) {
  code: 'ERR_UNSUPPORTED_PROTOCOL'
}
```

**Comment by GGAlanSmithee** [comment]
@brokenprogrammer thanks for reporting

Interesting. Your output shows one additional listening address. My (working) output is:

```bash
Listener ready, listening on:
/ip4/192.168.81.23/tcp/63688/p2p/QmZzRKpVkhE1oF2uh526VuSGK6UebxrRFK4RFg91p8UtWF
/ip4/127.0.0.1/tcp/63688/p2p/QmZzRKpVkhE1oF2uh526VuSGK6UebxrRFK4RFg91p8UtWF
```

I'm fumbling in the dark here, so will have to investigate, but maybe it has something to do with your network settings.

**Comment by GGAlanSmithee** [comment]
Also, @brokenprogrammer did you only run one instance on your computer? The line

```js
Discovered: {peerId}
````

indicates that you discovered a peer, which seems a bit strange.

**Comment by GGAlanSmithee** [comment]
Additional info: 

Seems likely that the issue is due to @brokenprogrammer having multicast enabled on his computer (using mdns with zeroconf). Will test this theory later, when I have a bit more time.

EDIT: The reason for this seems to be that port 5353 is the designated port for mdns. Other users have had similar issues with running multiple services on this protocol, though unrelated to libp2p

**Comment by GGAlanSmithee** [comment]
@brokenprogrammer I added a simplified `mdns` test in https://github.com/feldmanchain/feldmanchain-on-prem/pull/7/commits/52188f49a9a1f9cf5bf15410a80f38308c604564

Can you please pull it (latest commit on branch `feature/chat`) and run `npm run start:mdns-test`? Just to further isolate the issue. I am faily certain that is the source of the error, but just to make sure.

**Comment by GGAlanSmithee** [comment]
Here's the output when running the above example from a computer running win7 that's not on the office net:

![image](https://user-images.githubusercontent.com/11805103/143082299-a7461e83-2173-421c-ab00-881978509f89.png)

**Comment by GGAlanSmithee** [comment]
Interestingly, the peer that your computer discovered is the IPFS peer running on my computer:

![image](https://user-images.githubusercontent.com/11805103/143097864-da9f5806-b9d7-450e-9f7a-27fda40d8e9f.png)

This somewhat proves that we will be able to use this as a discovery mechanism for a on-prem installation of the feldmanchain, but it also shows that a libp2p peer defaults to a configuration compatible with IPFS. This is reasonable since they are behind this lib. Probably something to look into further though. I also doubt this has something to do with the actual issue discussed in this thread. I will turn off the node while testing.

**Comment by GGAlanSmithee** [comment]
@brokenprogrammer I actually think I am chasing ghosts, and that I should learn to read error messages.

The exception you posted points to
```ts
async Libp2p.<anonymous> (.../feldmanchain-on-prem/src/peer.js:48:22)
```

which corresponds to the line

```ts
const { stream } = await node.dialProtocol(peerId, "/chat/1.0.0")
```

In that context, the error message __does__ make sense, since in the code, we attempt to dial in to the protocol `/chat/1.0.0`. This is copy/pasted from an official example, so I expect it to work out of the box (as it does on my computers) but that is ofcourse an assumption, and this does provide me with something to look into further.

**Comment by GGAlanSmithee** [comment]
@brokenprogrammer 

I am quite certain I know what is happening now:

1. When you run the script, and it connects, it discovers my IPFS peer
2. On doing so, it attempts to dial into it (using its `peerId`) on the protocol `/chat/1.0.0`
3. Since my IPFS peer does not handle the protocol `/chat/1.0.0`, the proper error message - `ERR_UNSUPPORTED_PROTOCOL` -is returned.

If this is correct, you should be able to try this tomorrow and expect it to work (since my IPFS peer now is turned off). Please be aware that you do not discover any peer when running just one instance of the script.

This does not, however, explain why it failed on your other computer, since, if I understand it correctly, that one is **not** connected to the office net?

**Comment by brokenprogrammer** [comment]
I see that makes sense, I never ran it on my personal computer only on my work pc.

**Comment by GGAlanSmithee** [comment]
Ok, great, hopefully it works now then!

**Comment by GGAlanSmithee** [comment]
![image](https://user-images.githubusercontent.com/11805103/143195621-cef2aa6f-899b-4f40-9b13-6ca5685713fc.png)

Seems that was the issue indeed, and it seems to be working now :100:

I'll open a new issue regarding having only compatible peers discover each other
